on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: stacr.azurecr.io
        username: ${{ secrets.acr_stacr_username }}
        password: ${{ secrets.acr_stacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t stacr.azurecr.io/staks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push stacr.azurecr.io/staks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_staks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep staks-ns | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace staks-ns`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: staks-ns
        container-registry-url: stacr.azurecr.io
        container-registry-username: ${{ secrets.acr_stacr_username }}
        container-registry-password: ${{ secrets.acr_stacr_password }}
        secret-name: staksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: staks-ns
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          stacr.azurecr.io/staks:${{ github.sha }}
        imagepullsecrets: |
          staksdockerauth
